services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ${PROD_CONTAINER_NAME}
    restart: always
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    ports:
      - "${PROD_PORT}:8000"
    volumes:
      - ./app:/code/app
      - ./logs:/code/logs
    networks:
      - default # Оставляем default для возможных будущих сервисов в этом проекте

networks:
  default:
    driver: bridge
